sudo: required

services:
  - docker

env:
  global:
    - VERSION=4.0.1
    - GITHUB_REPO=crazy-max/docker-syntaxhighlighter
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=syntaxhighlighter
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=syntaxhighlighter
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/syntaxhighlighter/7sFfYaLyUpfAsds-XUq0ymCEkcw=
    - secure: yJWt1eM731a3czRP6ADrEwIb0cAvlaKW+Bt0erpblJtch8yYaHEdzgHDsaQvbKMtL2ludAuXlEEdE7/kEZb1uBrODM7DBex11UlT/xO20EPweiW3y2h0+0Bj2POkp97lUjVpXCAgUcx6m/OD5IjFSAzItTq8V6qfrxCwSmsvdRthbATBTpJmjPHrbQ+LMhjkCCZIrwvimpp08FjI6eoBoNVY7KzOZe+rqnxn1+Fq+Zl6MeQvPMWMJl9Tak3NnvPJNMuntx0ugEYaEQl0NBifGq+hPFPoO61paJPK7B3NPwUndgDk4TkaysxhPnyWVdiWg8TwfgBtRINJq36sTZpoYahB5cIBaZkG8aMZdKzu0IR2PifjJefjljlCyHUL8WRv5sfJcILtMMCOuPftqpGSlJ3LMUuwW0zLkQ+XQnhbXVRFZ5MIg2rfq0xdm8gIVMGLlzV0SjejP90uvL+JJoeMMABmHbPCjQgqmf0cRyetBb+gh+G3/WnY0UXacivVhU3VLcGeqPzGSbUiB/W1rm03lCeu+ibNd71KFX3MCQTBQx/Bs4NDWb7FcGCBYLLObanYHm4wxoQ1/2r7wCXTadbwocEwzblDpSINyhRhGzRTrIupROhi2Iw06fNhBm6EDWsvs5nO56oTY3ovigpGwYG/hJt/ZLoCSAL4j79LR10RiQo= # DOCKER_PASSWORD
    - secure: xVkE14jTjk1Imf4VqeJeucUMlyIKuF3HD5Yn5uCe5XgFjbMRS4S86YVIY6cUFqUpX/vSQGAEkAX2u7GtfPnNj9Geq0hjY/KL0lvvgk+SSE2sRXnf2+6lGfd1cqA+SbVW9Xp4X4GDD8XHKjdC4tgErjErvlDUjjMpvhQIstXcHDuI2W3NgZKbJSC6Sl1hPFGFsEwm4yCAfBezuJgOJNdHhgt2CTFt/0Iz+Qu/7/iAnsX/0lMoL5ia2EJFCRQDpqoufXtwNcp8FbucbMIDRhOoMjhmClCFZzu56XzpRTrmCE006X+mApICIlUzQnn+y+bs5IFqwYa9j8cIizbcaJ4EOoiwKkKANccSj1gacRCvlsaAbAi1NgbULQXSjOuxP2pxkGNh6SQ2VdwtJQta7bFo+slHU1OJEulp5WMb2hn7M51MivtcNxsTpdPA5Wn299fn1xUIyEeptbHvs0woSweNGLEQhfav+ul9jrVWhv8m1KrWgdeMp97SQRcUigS3hDUuLgb5bAq0tXOT+UiyQhgVnZoRSkVhwbEyFqqQx0jwwsgCa1giApa5UMTYif6yrT7TMiCgbzQMu1nvgXKgvL09MAFP2309cwrWO9ZHTcHQTLiO1nXXcDthilvJcT01SHkNUYpSkPGtjX2w6qmTQgTMpsQpwZvHtGgwtRX3mPT2yx4= # QUAY_PASSWORD
    - secure: gPGJ5KbOq4KrDHU/9Ml4IUJyF5XKOSV5NbpiXZ2YgztY9u6xfdA1dNYn/nmP1B1rBlXwetvaxslfdON5DOw2z8xfJ7un9RDcTHljbM6Hhexg3s5t9IazQZPppmtx5n6mB1GazgjU7KcyYB2FZzUzKRfmM5AFwrbvxQw0/Yg0+dEMdWzj7Ii5trKV8wB0GMbgIHlg18vhpr/Q9qisxHaP7ewhcESWktMVG43RwP7/K7qkUOJVQwhYhjWBY0X9q1VyMd/yOx1KRo3zZCXb6frzrxejlE+111nUDqq9iPv1oWN2oYi3B7VEJMGbJYe1U4xxHcvyFoocYI1VC4v8BONHQ6JB4lFkwBCQ2EvhBnwxO4if8sD2WdXosfMfvqDdmyPIRR9lOiV0b+JVm75M6w1OgHh6WA/ogWp5qZyKTL7ZQanMQIyVyfBM3/HPhYSKlaic+7P5iau73Togfr+m8uagmu9qtK81ZQpzWiHh7VY231gesMpOnjqqhUIA6gr3Q1SLrAvmhFzV8YOf9+TqLy8E0NwMl0qQgav8fpb2h6AsejsgOJeUQACAqOvZ6fbO4IgY5l8mgBsXbvsR9QZKO7ur/md5blz6SMDEzuS9PcN652Bkl+9yQNKtM0XpwGWNT41TlLoVzaDlTmXI+YYC6/NaQYzct9bwZ+kHTxsFi+cuu74= # GITHUB_TOKEN

before_install:
  - sudo apt-get update
  - docker --version
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export DOCKER_TAG=$(if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, DOCKER_TAG=$DOCKER_TAG"

install:
  - |
    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=${TRAVIS_COMMIT::8} \
    --build-arg VERSION=${VERSION} \
    -t docker_build .

install:
- |
    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=${TRAVIS_COMMIT::8} \
    --build-arg VERSION=${VERSION} \
    -t docker_build .

script:
  - docker run -it --rm --name $DOCKER_REPONAME -v "$(pwd)/sxh:/syntaxhighlighter/dist" docker_build
  - test -f ./sxh/syntaxhighlighter.js

after_success:
  - |
    test $TRAVIS_PULL_REQUEST = false \
    && echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin \
    && docker tag docker_build $DOCKER_USERNAME/$DOCKER_REPONAME:$DOCKER_TAG \
    && docker tag docker_build $DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION \
    && docker push $DOCKER_USERNAME/$DOCKER_REPONAME \
    && echo "$QUAY_PASSWORD" | docker login quay.io --username "$QUAY_USERNAME" --password-stdin \
    && docker tag docker_build quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME:$DOCKER_TAG \
    && docker tag docker_build quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME:$VERSION \
    && docker push quay.io/$QUAY_USERNAME/$QUAY_REPONAME \
    && curl -X POST $MICROBADGER_HOOK

branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    secure: cVvFiR6LFxQSgEaPjiBKABUsWBlbsB4eUt+TfbZGyVSsvvVA37nELUEFN1QgLv4BokHHuq4n8U962jRCZ5SdMvwo1Xzotx/lEsIajPN/ikzmBzAxj9aSfqK8CadQbJtvwx/mZVsCl3EZJIcTYnH0tbbc/+fZFZcxBbKhsLANa5NtCzXjWlfXE8XGcE2PeNqTyhuQQl6jrB48OLbXuM9IqdrlahQsG5BNVmzWkbut522ToIBrRlRWxyJlDEKm3Rxdr8NYYzpgc4jx7HFKijjDkXHdOeojTAe76BpfjpqnCNlTUL9Q0Iu8CwCr5rpR9P8hkRAIZuy4ONF8durmrc11qCjIStI84Bksc+sVAb1DMPdk0n30C2UC4r5f+vF3Pj9GpF4jQrmlPD7dCqHENLR+Fj0jdF68ZJiDn4AdBgPB6dOLN37rfQAPZoMvfwk+dThM2fDTZPEalLNFmyRa3Rc39wEfu3/RvyaNCVBW7zF5v35gVMrkcAOnHXtN0+j229mxJXZ6ixYdMP+O0bONoDgJqIHSYUlZeKoW3PCGbfIsHcZRQhxqHehM5yiD1l78lgObXJJjqK8rK0Dn1z3MVuBJ2hbeFbccfnKjYE/MC5Bx8nGfirRX9/hfxOZJqXdHvumr4kLMAM8jnXL2zdv2JXlWMfQb5jKvuEO5eD335zm2nd8=
